name: helloworld
on: push
jobs: 
  print-information: 
    runs-on: ubuntu-latest
    steps:
      - name: print helloworld
        run: echo "helloworld!"
      - name: print registration number
        run: echo "22cb010"
      - name: print name
        run: echo "K Barath Sriram"
